[package]
edition = "2018"
name = "config_path"
version = "0.1.0"

[[bin]]
name = 'config_path'
path = 'src/main.rs'

[dependencies]
anyhow = "1.0.40"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "2.1.0"
